name: flat_ui
description: Flat UI.
version: 0.1.1
homepage: https://github.com/ainulya16/flat_ui

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  intl: ^0.17.0
  tinycolor: ^1.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true


  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: packages/flat_ui/assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: packages/flat_ui/assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: packages/flat_ui/assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: packages/flat_ui/assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: packages/flat_ui/assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: packages/flat_ui/assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: packages/flat_ui/assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: packages/flat_ui/assets/fonts/OpenSans-Regular.ttf
        - asset: packages/flat_ui/assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: packages/flat_ui/assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
